### ISSUE TITLE
Updating iocage.

### ISSUE THREAD

**Issue by skarekrow** [pannon/iocage#11]
Hello, not sure if this is the right spot to post this but I'm unsure if you're the maintainer for iocage in the ports tree? If so, is there a particular reason it hasn't been updated past 1.4.4? I have it installed via the ports tree and was unsure of the correct process to replace it with the git version, so I figured I'd ask you if it's able to be updated in the ports tree.

**Comment by pannon** [comment]
It was a time constraint on the port maintainer's side. I have actually raised this just a couple of days ago. The outcome is that a PR needs to be raised in Bugzilla with patches and and then other people from the ports team can deal with the update.

For now you can just download the latest iocage and drop it in. It is just a shell script.

**Comment by skarekrow** [comment]
Alright thanks! I am in the process of going to 10.1 from 10.0 and 
figured I should update iocage so I can upgrade my jails smoothly. 
Appreciate the response as always Peter :)

**Comment by skarekrow** [comment]
Hm, it actually seems that the upgrade function might not be in there yet. I've never done this before, do you know a good process to manually upgrade the jails properly? Will `freebsd-update upgrade -r 10.x-RELEASE -b /iocage/jails/UUID/root.` be all I need to do?

**Comment by pannon** [comment]
Yes that's right, the RELEASE upgrade is not in yet - only jail updating on the same RELEASE  (patching) is supported right now. The upgrade command looks OK just make sure you snapshot the jail beforehand!

Also you there is a trick, you need to upgrade the jails first and then the host, otherwise freebsd-update will get confused.

I have tried to mitigate this and modified freebsd-update to support an extra cmd switch - which can be found in this repo.

**Comment by skarekrow** [comment]
Is it the freebsd-update/9.3 one? I assume I drop that in 
/usr/local/sbin to use it without overriding the official script, 
correct? Also what is the extra cmd switch that it has in it?

To recap and make sure I have this correct:

I upgrade the jails with freebsd-upgrade to 10.1
Do I need to reboot?
Then upgrade the host to 10.1
Another reboot?
Profit?

Thanks for helping me again!

**Comment by pannon** [comment]
Yes that's the one, has an extra switch "-o" to override the current RELEASE information - this will update the jail no matter what - to the the RELEASE you specify.

Your process is correct, you only need to reboot once, the last step.

**Comment by skarekrow** [comment]
Alright! Thanks man :) I'm going to take the dive now.

**Comment by skarekrow** [comment]
Went smoothly. All done now. The tag functionality works perfect by the way, great job!
