### ISSUE TITLE
running jail can be destroyed if referred by tag

### ISSUE THREAD

**Issue by abelbabel** [pannon/iocage#20]
A running jail can be destroyed when called by tag using `iocage destroy TAG`.
`jls` afterwards prooves that this jail is still running eventhough dataset, e.a. is missing ...

**Comment by abelbabel** [comment]
simple patch could be to remove this line in `__destroy_jail ()`

    local state="$(jls | grep $name | wc -l)"

and add this line after getting fulluuid

    local state="$(jls | grep $fulluuid | wc -l)"

**Comment by pannon** [comment]
Nice catch, this is a bug, needs fixing. I have tested this fix and works as you've described - would you like/mind to commit this bit?

**Comment by abelbabel** [comment]
I'm not into committing on github at the moment (haven't done it for a long time ... too long to remember ;) ). I could relearn it, but might take some time. I wouldn't be upset if you fix it in the meanwhile to squash the bug quickly.
