### ISSUE TITLE
freebsd-update behaves different/strange

### ISSUE THREAD

**Issue by abelbabel** [pannon/iocage#21]
When running `iocage update UUID` `freebsd-update` does different things as when running

    iocage chroot UUID
    freebsd-update fetch install

Why?

**Comment by pannon** [comment]
It is doing essentially the same thing, but with the help of `freebsd-update -b`. It also creates a ZFS snapshot for rollback.

**Comment by abelbabel** [comment]
Maybe my observations only appear when host and jail RELEASE are out of sync?!
I had 10.1 on host and 9.1 in jail and observed different behaviour of freebsd-update. But I will recheck it.

**Comment by pannon** [comment]
That will be tricky, it boils down to freebsd-update not being able to handle updates/upgrades properly for jails if the host is RELEASE is higher than the jails. I have tried to mitigate this, there is a modified freebsd-update in this repo and it supports -o flag to override the RELEASE manually.

**Comment by abelbabel** [comment]
OK. I rechecked it. Had different outputs even with same RELEASE. But I think the reason is that `iocage update` operates on `/var/db/freebsd-update` of host and the other method on `/var/db/freebsd-update` in jail. This would mean that all jails will be updated from same `/var/db/freebsd-update` if you use `iocage update`. Can this cause troubles?

**Comment by pannon** [comment]
This is interesting I had the impression that the `-b` flag for `freebsd-update` will use `var/db/freebsd-update` under the jail.

**Comment by skarekrow** [comment]
Well looking at freebsd-update(8) it doesn't seem to be the case @pannon. 

```    
-b basedir   Operate on a system mounted at basedir.  (default: /, or as
                  given in the configuration file.)

-d workdir   Store working files in workdir.  (default:
                  /var/db/freebsd-update/, or as given in the configuration
                  file.)
```
It sounds like even though we are changing the basedir, it is still using /var/db/freebsd-update. Unless I'm interpreting that wrong and it's "chrooting" and so /var/db/freebsd-update is actually /usr/jails/JAIL/var/db/freebsd-update.

**Comment by pannon** [comment]
Confirmed, yes by default it will use `/var/db/freebsd-update/` even if `-b` is specified. Should not cause issues unless jails are updated in parallel, this is just an assumption have not tested.

There is a little bit of work required to make the update process execute this:
```  
freebsd-update -b /iocage/jails/UUID/root -d /iocage/jails/UUID/root/var/db/freebsd-update/ action
```

Will try to fix the update process, also someone emailed an interesting suggestion around the use of `$UNAME_r` to override the RELEASE information for `freebsd-update`. Will try to get this in as well.

**Comment by skarekrow** [comment]
This can probably be closed now?
