### ISSUE TITLE
Running "iocage fetch" on 10.0-STABLE does not work

### ISSUE THREAD

**Issue by keltia** [pannon/iocage#26]
Hello, running iocage 1.4.6 on a 10.0-STABLE system and trying to bootstrap iocage on it.

    FreeBSD oldnext.keltia.net 10.0-STABLE FreeBSD 10.0-STABLE #0 r269515: Mon Aug  4 18:46:44 CEST 2014     root@centre.keltia.net:/usr/obj/usr/src/sys/GENERIC  amd64

    1293 [14:47] root@oldnext:10.1-RELEASE/root# iocage fetch
    Supported releases are:
       10.1-RELEASE
       10.0-RELEASE
        9.3-RELEASE
        9.2-RELEASE
        9.1-RELEASE
    Please select a release [10.0-STABLE]: 10.1-RELEASE
    Exctracting: base.txz
    Exctracting: doc.txz
    Exctracting: lib32.txz
    * Updating base jail..
    Looking up update.FreeBSD.org mirrors... 5 mirrors found.
    Fetching metadata signature for 10.0-STABLE from update5.freebsd.org... failed.
    Fetching metadata signature for 10.0-STABLE from update6.freebsd.org... failed.
    Fetching metadata signature for 10.0-STABLE from update3.freebsd.org... failed.
    Fetching metadata signature for 10.0-STABLE from update4.freebsd.org... failed.
    Fetching metadata signature for 10.0-STABLE from update2.freebsd.org... failed.
    No mirrors remaining, giving up.
    No updates are available to install.
    Run '/usr/local/sbin/ioc-freebsd-update fetch' first.

There is no /usr/local/sbin/ioc-freebsd-update anyway…

Same issue when trying to install 10.0-RELEASE instead.

(BTW notice the "exctracting" above)

What did I miss?

**Comment by skarekrow** [comment]
I'm on my phone at the moment so I will check when I get on a desktop as I
believe I also fixed those typos. Have you tried the latest git master?
Also AFAIK you can't run a newer release jail on a older version. So I
wouldn't expect this to work. @pannon what do you think?

**Comment by pannon** [comment]
This is to do with 10.0-STABLE not being available on FreeBSD FTP servers. Try to override it to 10.1-RELEASE.

**Comment by skarekrow** [comment]
Right, but that's assuming his 10.0-STABLE has a higher revision then 10.1-RELEASE correct?
On 3/3/2015 1:20:15 PM, Peter Toth <notifications@github.com> wrote:
This is to do with 10.0-STABLE not being available on FreeBSD FTP servers. Try to override it to 10.1-RELEASE.
&mdash;

**Comment by pannon** [comment]
This is only seem to affect STABLE.

**Comment by keltia** [comment]
I tried b both 10.0-RELEASE and 10.1-RELEASE, exact same result

**Comment by skarekrow** [comment]
Have you tried ```env UNAME_r="10.1-RELEASE" iocage fetch```? I haven't personally tested this as I run RELEASE systems, but I think it should work.

**Comment by keltia** [comment]
No change, sorry.

**Comment by skarekrow** [comment]
That prefix is because the script makes it's own freebsd-update program and then calls that. I updated it since then to use a better method. Try running a ```git clone https://github.com/pannon/iocage.git``` and running that iocage as root to see if that helps. So it would look like this:

```cd /wherever/you/did/the/git/clone```
as root run ```./iocage fetch```

Then when you select 10.1-RELEASE it should work. No need for you to do env UNAME_r or anything. Just exactly what I typed above. If that does work, feel free to replace the existing iocage things with the git cloned objects.

**Comment by keltia** [comment]
It is working, thanks.  Only got some zfs warning (see below)

1336 [23:15] root@oldnext:/tmp/iocage# ./iocage fetch
    Supported releases are:
       10.1-RELEASE
       10.0-RELEASE
        9.3-RELEASE
        9.2-RELEASE
        9.1-RELEASE
  Please select a release [10.0-STABLE]: 10.1-RELEASE
    base.txz                                      100% of   63 MB 8954 kBps 00m08s
    doc.txz                                       100% of 1395 kB 6397 kBps 00m00s
    lib32.txz                                     100% of   15 MB 9522 kBps 00m02s
    Extracting: base.txz
    Extracting: doc.txz
    Extracting: lib32.txz
    * Updating base jail..
    Looking up update.FreeBSD.org mirrors... 5 mirrors found.
    Fetching public key from update6.freebsd.org... done.
    Fetching metadata signature for 10.1-RELEASE from update6.freebsd.org... done.
    Fetching metadata index... done.
    Fetching 2 metadata files... done.
    Inspecting system... done.
    Preparing to download files... done.
    Fetching 715     patches.....10....20....30....40....50....60....70....80....90....100....110....120....130....140....150....160....170.. ..180....190....200....210....220....230....240....250....260....270....280....290....300....310....320....330....340....350....360....370....380....390....400....410....420....430....440....450....460....470....480....490....500....510....520....530....540....550....560....570....580....590....600....610....620....630....640....650....660....670....680....690....700....710.. done.
    Applying patches... done.
    Fetching 10 files... done.
    Installing updates... done.
    ./.zfs/: Can't restore time
    ./.zfs/snapshot/: Can't create '.zfs/snapshot'
    ./.zfs/shares/: Can't create '.zfs/shares'
    tar: Error exit delayed from previous errors.

**Comment by skarekrow** [comment]
Great! Is that a clean ZFS dataset? Seems like a ZFS issue and not iocage.
@pannonp thoughts?

**Comment by keltia** [comment]
Yeah, I did a `zfs destroy -r` on the `tank/iocage` dataset before.

**Comment by skarekrow** [comment]
Like Peter said on Twitter I also have never seen this before. Perhaps
Google is the only answer?

**Comment by pannon** [comment]
Looks like tar misbehaving... Maybe my tar commit done yesterday for the basejails. Will need to test this on my setup.

**Comment by pannon** [comment]
Please could you post the output for `zfs get snapdir filesystem` ? Should be set to hidden by default.

**Comment by pr1ntf** [comment]
I can confirm this is part of the __create_basejail $release tar stuff. 
I was receiving the error: 

        ./usr/bin/chgrp: Can't create usr/bin/chgrp
        tar: Error exit delayed from previous errors.

At first I thought it had to do with line 554 of iocage:

        cp $iocroot/releases/$release/root/usr/sbin/chown \   
        $iocroot/base/$release/root/usr/bin/chgrp

But even after commenting it out I still got the error. 

I then commented out all of __create_basejail $release and it worked. 
A yolo band-aid, but it works for now.

**Comment by skarekrow** [comment]
The chgrp command does exist afterwards. It is originally a hard link and
with basejails it can't traverse filesystems. I think this is cosmetic.

**Comment by pr1ntf** [comment]
It is there for me as well.

**Comment by skarekrow** [comment]
Also @pr1ntf the original tar issue as described here has been fixed. Since I'm not on my phone I will elaborate on my previous post. What you're seeing is not the same thing. You're witnessing tar show that error because /usr/bin/chgrp is a hardlink to /usr/sbin/chown. Since hardlinks can't traverse filesystems, they break on the basejail setup. So what you see is tar complaining because we told it to exclude /usr/bin/chgrp as we recreate it afterwards.
