### ISSUE TITLE
filesystems left around

### ISSUE THREAD

**Issue by dlangille** [pannon/iocage#28]
This is long because it might be relevant.  I started playing with iocage today:

<pre>
$ sudo iocage fetch
  please select a pool for iocage jails [system]: system/jails
cannot open 'system/jails': invalid character '/' in pool name
Supported releases are: 
   10.1-RELEASE
   10.0-RELEASE
    9.3-RELEASE
    9.2-RELEASE
    9.1-RELEASE
Please select a release [10.1-RELEASE]: 
<pre>

I realize now that it was asking for a pool, not a filesystem.

Now we have:

<pre>
system/jails/iocage                              509M   435G    96K  /iocage
system/jails/iocage/download                    80.7M   435G    96K  /iocage/download
system/jails/iocage/download/10.1-RELEASE       80.6M   435G  80.6M  /iocage/download/10.1-RELEASE
system/jails/iocage/jails                         96K   435G    96K  /iocage/jails
system/jails/iocage/releases                     428M   435G    96K  /iocage/releases
system/jails/iocage/releases/10.1-RELEASE        428M   435G    96K  /iocage/releases/10.1-RELEASE
system/jails/iocage/releases/10.1-RELEASE/root   428M   435G   428M  /iocage/releases/10.1-RELEASE/root
</pre>

Let's try a jail:

<pre>
$ sudo iocage create tag=wiki.bsdcan.org
  please select a pool for iocage jails [system]: system/jails
cannot open 'system/jails': invalid character '/' in pool name
Configuring jail..
</pre>

Now we have:

<pre>
system/jails/iocage                                                        937M   435G   104K  /iocage
system/jails/iocage/download                                              80.7M   435G    96K  /iocage/download
system/jails/iocage/download/10.1-RELEASE                                 80.6M   435G  80.6M  /iocage/download/10.1-RELEASE
system/jails/iocage/jails                                                  428M   435G    96K  /iocage/jails
system/jails/iocage/jails/61abf3f6-c429-11e4-8494-00259094119e             428M  14.6G    96K  /iocage/jails/61abf3f6-c429-11e4-8494-00259094119e
system/jails/iocage/jails/61abf3f6-c429-11e4-8494-00259094119e/root        428M  14.6G   428M  /iocage/jails/61abf3f6-c429-11e4-8494-00259094119e/root
system/jails/iocage/jails/61abf3f6-c429-11e4-8494-00259094119e/root/data    96K  14.6G    96K  none
system/jails/iocage/releases                                               428M   435G    96K  /iocage/releases
system/jails/iocage/releases/10.1-RELEASE                                  428M   435G    96K  /iocage/releases/10.1-RELEASE
system/jails/iocage/releases/10.1-RELEASE/root                             428M   435G   428M  /iocage/releases/10.1-RELEASE/root
</pre>

Ahh, no IP address on that jail.  Let's remove it:

<pre>
iocage destroy tag=wiki.bsdcan.org
cannot open 'system/iocage/jails': dataset does not exist
  ERROR: tag=wiki.bsdcan.org not found
</pre>

Let's try this command:

<pre>
$ sudo iocage df
cannot open 'system/iocage/jails': dataset does not exist
UUID                                  CRT     RES    QTA    USE    AVA  </pre>

Let's start it:

<pre>
$ sudo iocage start 61abf3f6
cannot open 'system/iocage/jails': dataset does not exist
  ERROR: 61abf3f6 not found
</pre>

OK.  I'm getting nowhere.  Let's start fresh.

<pre>
$ sudo zfs destroy -r system/jails/iocage
$ sudo zfs destroy -r system/jails
$ sudo iocage fetch
Supported releases are: 
   10.1-RELEASE
   10.0-RELEASE
    9.3-RELEASE
    9.2-RELEASE
    9.1-RELEASE
Please select a release [10.1-RELEASE]: 
base.txz                                      100% of   63 MB   10 MBps 00m06s
doc.txz                                       100% of 1395 kB 6768 kBps 00m00s
lib32.txz                                     100% of   15 MB    9 MBps 00m02s
Exctracting: base.txz
Exctracting: doc.txz
Exctracting: lib32.txz
* Updating base jail..
Looking up update.FreeBSD.org mirrors... 5 mirrors found.
Fetching metadata signature for 10.1-RELEASE from update5.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

The following files will be added as part of updating to 10.1-RELEASE-p6:
/usr/src/crypto/openssl/util/mkbuildinf.pl

The following files will be updated as part of updating to 10.1-RELEASE-p6:
/bin/freebsd-version
/lib/libc.so.7
/lib/libcrypto.so.7
/rescue/[
/rescue/atmconfig
...
...
/rescue/fsck_msdosfs
Installing updates...install: /iocage/releases/10.1-RELEASE/root//usr/src/crypto/openssl/util/mkbuildinf.pl: No such file or directory
 done.
</pre>

Now we have:

<pre>
system/iocage                              509M   436G    96K  /iocage
system/iocage/download                    80.7M   436G    96K  /iocage/download
system/iocage/download/10.1-RELEASE       80.6M   436G  80.6M  /iocage/download/10.1-RELEASE
system/iocage/jails                         96K   436G    96K  /iocage/jails
system/iocage/releases                     428M   436G    96K  /iocage/releases
system/iocage/releases/10.1-RELEASE        428M   436G    96K  /iocage/releases/10.1-RELEASE
system/iocage/releases/10.1-RELEASE/root   428M   436G   428M  /iocage/releases/10.1-RELEASE/root
</pre>

Create a jail:

<pre>
sudo iocage create tag=wiki.bsdcan.org
</pre>

Oh wait, still no IP address.  Delete:

<pre>
$ sudo iocage destroy wiki.bsdcan.org
 
  WARNING: this will destroy jail 863749f1-c42e-11e4-8494-00259094119e
  Dataset: system/iocage/jails/863749f1-c42e-11e4-8494-00259094119e
 
  Are you sure ? Y[n]: y
</pre>

Note that the filesystem was not delete:

<pre>
system/iocage                                                        937M   435G   108K  /iocage
system/iocage/download                                              80.7M   435G    96K  /iocage/download
system/iocage/download/10.1-RELEASE                                 80.6M   435G  80.6M  /iocage/download/10.1-RELEASE
system/iocage/jails                                                  428M   435G    96K  /iocage/jails
system/iocage/jails/863749f1-c42e-11e4-8494-00259094119e             428M  14.6G    96K  /iocage/jails/863749f1-c42e-11e4-8494-00259094119e
system/iocage/jails/863749f1-c42e-11e4-8494-00259094119e/root        428M  14.6G   428M  /iocage/jails/863749f1-c42e-11e4-8494-00259094119e/root
system/iocage/jails/863749f1-c42e-11e4-8494-00259094119e/root/data    96K  14.6G    96K  none
</pre>

Let's try with an IP:

<pre>
$ sudo iocage create tag=wiki.bsdcan.org ip4_addr="em0|199.233.228.195,10.0.0.228"
Configuring jail..
** interfaces=vnet0:bridge0,vnet1:bridge1
** vnet=off
...
...
* wallclock=off
** tag=wiki.bsdcan.org
  ERROR: tag already exists, can not symlink: wiki.bsdcan.org
</pre>

Eh?  How can I remove that tag so I can create?

Let's try delete:

<pre>
$ sudo iocage destroy aab66d9e
 
  WARNING: this will destroy jail aab66d9e-c430-11e4-8494-00259094119e
  Dataset: system/iocage/jails/aab66d9e-c430-11e4-8494-00259094119e
 
  Are you sure ? Y[n]: n
</pre>

But I see:

<pre>
system/iocage                                                       1.33G   435G   108K  /iocage
system/iocage/download                                              80.7M   435G    96K  /iocage/download
system/iocage/download/10.1-RELEASE                                 80.6M   435G  80.6M  /iocage/download/10.1-RELEASE
system/iocage/jails                                                  856M   435G    96K  /iocage/jails
system/iocage/jails/863749f1-c42e-11e4-8494-00259094119e             428M  14.6G    96K  /iocage/jails/863749f1-c42e-11e4-8494-00259094119e
system/iocage/jails/863749f1-c42e-11e4-8494-00259094119e/root        428M  14.6G   428M  /iocage/jails/863749f1-c42e-11e4-8494-00259094119e/root
system/iocage/jails/863749f1-c42e-11e4-8494-00259094119e/root/data    96K  14.6G    96K  none
system/iocage/jails/aab66d9e-c430-11e4-8494-00259094119e             428M   435G    96K  /iocage/jails/aab66d9e-c430-11e4-8494-00259094119e
system/iocage/jails/aab66d9e-c430-11e4-8494-00259094119e/root        428M   435G   428M  /iocage/jails/aab66d9e-c430-11e4-8494-00259094119e/root
system/iocage/releases                                               428M   435G    96K  /iocage/releases
system/iocage/releases/10.1-RELEASE                                  428M   435G    96K  /iocage/releases/10.1-RELEASE
system/iocage/releases/10.1-RELEASE/root                             428M   435G   428M  /iocage/releases/10.1-RELEASE/root

 sudo iocage show
UUID                                  
863749f1-c42e-11e4-8494-00259094119e    ERROR: mising UUID!
aab66d9e-c430-11e4-8494-00259094119e    ERROR: mising UUID!
[dan@tallboy /usr/local/etc]$ sudo iocage runtime 863749f1
jls: jail "ioc-863749f1-c42e-11e4-8494-00259094119e" not found
 ERROR: jail 863749f1-c42e-11e4-8494-00259094119e is not up..
</pre>

**Comment by skarekrow** [comment]
The issue is you are using a lowercase 'y'. Make sure to use a uppercase 'Y' instead.

**Comment by dlangille** [comment]
Really?  No warning, no message  *sigh*

**Comment by skarekrow** [comment]
Yeah that got me at first too. But it's there so you deliberately destroy something and don't accidentally hit 'y'. I may look into adding a message asking if you're sure when you do a 'y' and no message if you do 'Y'. After the other stuff we are doing at the moment.

**Comment by dlangille** [comment]
see https://github.com/pannon/iocage/pull/29

**Comment by dlangille** [comment]
BTW, do we have an IRC channel somewhere?

**Comment by skarekrow** [comment]
I do not have write privileges yet on the repo, so I cannot merge. Thanks for the commit though! As far as IRC goes, no. We have a Google Group, but it's really just myself and @pannon who have used it a bit. We have been using Twitter as of late.

**Comment by pr1ntf** [comment]
Interesting thread. I have been working on hacking at iocage so it doesn't
need its own pool at fetch. I started a fork, iocagep that I need to push
to my github account.
Also, @pr1ntf on the twitter.

**Comment by dlangille** [comment]
It doesn't seem to need its own pool though... I used an existing pool and it created it's own filesystem hanging off that.  Is that not what you're doing?

**Comment by dlangille** [comment]
FYI, I am on the #iocage channel on FreeNode.

**Comment by skarekrow** [comment]
Odd I just tried joining and it says the network is unavailable.

**Comment by pr1ntf** [comment]
I thought that would break things since there are lots of references to
/iocage in the script.
I got into the freenode just now.
