### ISSUE TITLE
IP addresses added via em0|199.233.228.195 are not removed when jail is stopped

### ISSUE THREAD

**Issue by dlangille** [pannon/iocage#30]
Should IP addresses of the form "em0|199.233.228.195" be added and removed dynamically?

I expect em1 to be the same before and after starting then stopping this jail.

<pre># iocage get ip4_addr wiki.bsdcan.org
em1|199.233.228.195,em1|10.0.0.228
# ifconfig em1
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=4219b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MAGIC,VLAN_HWTSO>
	ether 00:25:90:94:11:9f
	inet 199.233.228.194 netmask 0xfffffff8 broadcast 199.233.228.199 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect (100baseTX <full-duplex>)
	status: active
# iocage start wiki.bsdcan.org 
* Starting 983c693f-c447-11e4-8494-00259094119e (wiki.bsdcan.org)
  + Started (shared IP mode) OK
  + Starting services        OK
[root@tallboy ~]# ifconfig em1
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=4219b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MAGIC,VLAN_HWTSO>
	ether 00:25:90:94:11:9f
	inet 199.233.228.194 netmask 0xfffffff8 broadcast 199.233.228.199 
	inet 199.233.228.195 netmask 0xffffffff broadcast 199.233.228.195 
	inet 10.0.0.228 netmask 0xffffffff broadcast 10.0.0.228 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect (100baseTX <full-duplex>)
	status: active
[root@tallboy ~]# iocage stop wiki.bsdcan.org 
* Stopping 983c693f-c447-11e4-8494-00259094119e (wiki.bsdcan.org)
  + Running pre-stop         OK
  + Stopping services        OK
  + Removing jail process    OK
  + Running post-stop        OK
[root@tallboy ~]# ifconfig em1
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=4219b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MAGIC,VLAN_HWTSO>
	ether 00:25:90:94:11:9f
	inet 199.233.228.194 netmask 0xfffffff8 broadcast 199.233.228.199 
	inet 199.233.228.195 netmask 0xffffffff broadcast 199.233.228.195 
	inet 10.0.0.228 netmask 0xffffffff broadcast 10.0.0.228 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect (100baseTX <full-duplex>)
	status: active
[root@tallboy ~]# 
</pre>

**Comment by pannon** [comment]
@dlangille this should be handled now, please test and let me know.
