### ISSUE TITLE
check jail exists before attempting snapshot

### ISSUE THREAD

**Issue by dlangille** [pannon/iocage#31]
This jail tag is incorrect:

<pre>
# iocage snapshot "wiki.bscan.org@testing"
[: ==: unexpected operator
cannot open '': invalid dataset name
usage:
	snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
</pre>

The correct tag is wiki.bsdcan.org

Should we check that the jail exists first?

**Comment by pannon** [comment]
This is fixed now.
