### ISSUE TITLE
How do I find the snapshot directory for a given jail?

### ISSUE THREAD

**Issue by dlangille** [pannon/iocage#32]
'ls -h path' gives us /iocage/UUID/root

Can we always assume the snapshots for that jail are in /iocage/UUID/.zfs/snapshot?

I ask because I want to backup my jails by snapshot.  see https://gist.github.com/dlangille/dac3b6d138bb12874f9a#file-jail-snapshots-for-backup-sh

Given that directory, we can always do this to get the filesystem name with this command:

<pre>
# /sbin/zfs get -H -o name mountpoint /iocage/jails/983c693f-c447-11e4-8494-00259094119e/root
system/iocage/jails/983c693f-c447-11e4-8494-00259094119e/root
</pre>

**Comment by skarekrow** [comment]
AFAIK that is a safe stable directory unless removed by you.   They seem to
exist both in  the uuid/.zfs/snapshot/snapname directory and the
uuid/root/.zfs/snapshot/snapname directory.

**Comment by pannon** [comment]
With `iocage snapshot tag@snapname` iocage will recursively snapshot with the help of `zfs snapshot -r`. Jails consist of three ZFS datasets `pool/iocage/UUID`, `pool/iocage/UUID/root` and  `pool/iocage/UUID/root/data`. All of these will have a `.zfs` directory with snapshots. To backup a jail only the one under  `pool/iocage/UUID/root` is required unless the `data` ZFS filesystem is used as well.

There is a known issue with the length of pathnames on FreeBSD - you will most likely encounter this if diving into snapshots.

**Comment by pannon** [comment]
For reference https://github.com/pannon/iocage/issues/5

**Comment by dlangille** [comment]
Seems to be a configurable item: _PC_PATH_MAX
	     The maximum number	of bytes in a pathname.

https://www.freebsd.org/cgi/man.cgi?query=fpathconf&sektion=2&manpath=FreeBSD+4.8-RELEASE

**Comment by pannon** [comment]
Intriguing! Also if you want to get the mountpoint for a jail just use `iocage get mountpoint UUID|TAG`

**Comment by dlangille** [comment]
There are two issues: mountpoints and filepaths.

From IRC: "there are 2 things. the max length of a 'mount' point (60 something characters), and then the max path name (255 iirc)"

**Comment by dlangille** [comment]
That will be useful:

<pre>
$ sudo iocage get mountpoint wiki.bsdcan.org
/iocage/jails/983c693f-c447-11e4-8494-00259094119e
$ </pre>

**Comment by pannon** [comment]
The "mount' point (60 something characters)" issue is the culprit, and it is a painful one with ZFS snapshots. This is a global issue affecting others with a lot of nested or long name ZFS filesystems. There was a discussion way back about raising this limit - but never happened for some reason. Maybe too obtrusive and brakes in unexpected ways..

**Comment by kapsel** [comment]
I was the one that opened #5 a long time ago. I think it should be a lot less characters.

I personally know 3-4 people that refused using iocage because of the very long uuid's.

It's a problem for me on a daily basis (well, weekly), as I'm unable to access snapshots without taking the jail down and mounting it in the host instead.

I was thinking of doing a fork where this was different but I really think would be a lot better changing it in iocage or at least make some sort of option/workaround for it.

**Comment by pannon** [comment]
As a workaround the mountpoint UUID could be shortened, preserving the full UUID on the ZFS dataset itself, I believe this should work. Will commit a change to allow this. Still this is a FreeBSD specific problem, both Linux and Illumos have a much higher limit.

Unfortunately I did not have the time to file a bug for FreeBSD..

**Comment by pannon** [comment]
Just to add to this, this is not braking any path issues inside the jails. This is only affecting the "diving" into ZFS snapshots and only if the mounts are too long.

The jails are unaffected, and snapshot rollback works without issues.
