### ISSUE TITLE
Is there a command to list fetched releases?

### ISSUE THREAD

**Issue by dlangille** [pannon/iocage#33]
Other than doing this, how can I see what releases are already present?

<pre>
[root@tallboy ~]# zfs list -r   /iocage/releases
NAME                                       USED  AVAIL  REFER  MOUNTPOINT
system/iocage/releases                     428M   436G    96K  /iocage/releases
system/iocage/releases/10.1-RELEASE        428M   436G    96K  /iocage/releases/10.1-RELEASE
system/iocage/releases/10.1-RELEASE/root   428M   436G   428M  /iocage/releases/10.1-RELEASE/root
[root@tallboy ~]# 
</pre>

**Comment by pannon** [comment]
Will add a `iocage list -r` for this.

**Comment by pannon** [comment]
`iocage list -r` now works.
