### ISSUE TITLE
Strange behaviour of network connection

### ISSUE THREAD

**Issue by zenny** [pannon/iocage#51]
On a development machine (under KVM), iocage and related networking worked fine till the machine was shut down. When I restarted the machine again, the jails stopped getting access to the outside network (intra- and internet), however jails can ping host and vice versa.

# pfctl -s all
No ALTQ support in kernel
ALTQ related functions disabled
TRANSLATION RULES:
nat on em0 inet from ! 192.168.10.199 to any -> 192.168.10.199
rdr on em0 inet proto tcp from any to any port = http -> 10.1.1.20 port 80

FILTER RULES:
scrub on em0 all fragment reassemble
block drop log all
block drop in quick from <ossec_fwtable> to any
block drop in quick from <abusive_hosts> to any
block drop in quick from <hackers> to any
block drop out quick from any to <ossec_fwtable>
pass quick on em0:broadcast all flags S/SA modulate state
pass out quick on em0 all flags S/SA modulate state
pass log on em0 proto tcp from any to any port = ssh flags S/SA keep state
pass log on em0 proto tcp from any to any port = http flags S/SA keep state
pass log on em0 proto tcp from any to any port = https flags S/SA keep state
pass log on em0 proto udp from any to any port = ssh keep state
pass log on em0 proto udp from any to any port = http keep state
pass log on em0 proto udp from any to any port = https keep state
pass in inet proto icmp all icmp-type echoreq keep state

STATES:
all tcp 192.168.10.199:22 <- 192.168.10.3:37119       ESTABLISHED:ESTABLISHED

INFO:
Status: Enabled for 0 days 00:06:18           Debug: Urgent

Interface Stats for em0               IPv4             IPv6
  Bytes In                          551886                0
  Bytes Out                         256720                0
  Packets In
    Passed                            3756                0
    Blocked                            338                0
  Packets Out
    Passed                            1522                0
    Blocked                             19                0

State Table                          Total             Rate
  current entries                        1               
  searches                            1085            2.9/s
  inserts                                4            0.0/s
  removals                               3            0.0/s
Counters
  match                                313            0.8/s
  bad-offset                             0            0.0/s
  fragment                               0            0.0/s
  short                                  0            0.0/s
  normalize                              0            0.0/s
  memory                                 0            0.0/s
  bad-timestamp                          0            0.0/s
  congestion                             0            0.0/s
  ip-option                              0            0.0/s
  proto-cksum                            0            0.0/s
  state-mismatch                         0            0.0/s
  state-insert                           0            0.0/s
  state-limit                            0            0.0/s
  src-limit                              0            0.0/s
  synproxy                               0            0.0/s

TIMEOUTS:
tcp.first                   120s
tcp.opening                  30s
tcp.established           86400s
tcp.closing                 900s
tcp.finwait                  45s
tcp.closed                   90s
tcp.tsdiff                   30s
udp.first                    60s
udp.single                   30s
udp.multiple                 60s
icmp.first                   20s
icmp.error                   10s
other.first                  60s
other.single                 30s
other.multiple               60s
frag                         30s
interval                     10s
adaptive.start             6000 states
adaptive.end              12000 states
src.track                     0s

LIMITS:
states        hard limit    10000
src-nodes     hard limit    10000
frags         hard limit     5000
table-entries hard limit   200000

TABLES:
abusive_hosts
hackers
ossec_fwtable
ssh_abusers

OS FINGERPRINTS:
710 fingerprints loaded

# /etc/pf.conf is as follows:

# cat /etc/pf.conf
# MACROS --------------------------------
if  = "{" em0 "}"
int_if = "{" bridge epair vnet "}"

# TABLES --------------------------------

table <ossec_fwtable> persist #ossec_fwtable
table <abusive_hosts> persist
table <ssh_abusers> persist

table <hackers> persist file "/etc/hackers"

# don't filter on the loopback, VNET and bridge
set skip on lo
set skip on vnet
set skip on bridge
set skip on epair

set loginterface em0

# TRAFFIC NORMALIZATION ------------------
scrub on $if all fragment reassemble

# QUEUEING -------------------------------

# TRANSLATION ----------------------------
nat on em0 inet from ! em0 to any -> em0

# port forward http to jail (varnish)
rdr on $if inet proto tcp to port 80 -> 10.1.1.20 port 80

# PACKET FILTERING -----------------------

# setup a default deny policy
block log all
block in quick from <ossec_fwtable> to any
block out quick from any to <ossec_fwtable>
block in quick from <abusive_hosts>
block in quick from <hackers>

# pass broadcast
pass quick on em0:broadcast from any to any modulate state

# pass all traffic to and from the local network.
pass out quick on $if from any to any modulate state

# allow SSH and http/https
pass log on $if proto { tcp udp } from any to any port { ssh http 443 } keep state

# allow ping
pass in inet proto icmp all icmp-type echoreq

# /etc/rc.conf looks like:

# cat /etc/rc.conf
zfs_enable="YES"
sendmail_enable="NONE"
sshd_enable="YES"
hostname="freebsd10-dev"
#ifconfig_em0="inet 192.168.10.199 netmask 255.255.255.0"
ifconfig_em0="DHCP"
default_router="192.168.10.254"

cloned_interfaces="bridge0 bridge1"
ifconfig_bridge0="addm em0 10.1.1.254/24 up"

pf_enable="YES"
pf_rules="/etc/pf.conf"
pflog_enable="YES"
firewall_enable="YES"
firewall_type="open"
iocage_enable="YES"

# INSIDE JAIL, /etc/rc.conf looks like:

# cat /etc/rc.conf
hostname="3d4c116a-d1b4-11e4-8c1e-55ff3853a5bc"

cron_flags=" -J 15"

# Disable Sendmail by default
sendmail_enable="NONE"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

# Run secure syslog
syslogd_flags="-c -ss"

# Enable IPv6
ipv6_activate_all_interfaces="YES"

# Configure vnet0
ifconfig_vnet0="10.1.1.20/24"

# Set default GW to point to bridge0 IP
defaultrouter="10.1.1.254"

# Set IPFW to allow all
firewall_enable="YES"
firewall_type="open"

# Besides, when I try to restart network manually (service netif restart), it gives a known error (vnet issue for information only):

Created clone interfaces: bridge0 bridge1.
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ipv6_prefix_vnet0:3...}: Bad substitution
eval: ${ipv6_ifconfig_vnet0:3...}: Bad substitution
eval: ${ipv4_addrs_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ipv4_addrs_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ipv4_addrs_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ipv6_prefix_vnet0:3...}: Bad substitution
eval: ${ipv6_ifconfig_vnet0:3...}: Bad substitution
eval: ${wlans_vnet0:3...}: Bad substitution
eval: ${vlans_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet0:3...}: Bad substitution
eval: ${ipv6_prefix_vnet0:3...}: Bad substitution
eval: ${ipv6_ifconfig_vnet0:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ipv6_prefix_vnet1:3...}: Bad substitution
eval: ${ipv6_ifconfig_vnet1:3...}: Bad substitution
eval: ${ipv4_addrs_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ipv4_addrs_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ipv4_addrs_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ipv6_prefix_vnet1:3...}: Bad substitution
eval: ${ipv6_ifconfig_vnet1:3...}: Bad substitution
eval: ${wlans_vnet1:3...}: Bad substitution
eval: ${vlans_vnet1:3...}: Bad substitution
eval: ${ifconfig_vnet1:3...}: Bad substitution
eval: ${ipv6_prefix_vnet1:3...}: Bad substitution
eval: ${ipv6_ifconfig_vnet1:3...}: Bad substitution
ifconfig: BRDGADD em0: File exists

Strange that the networking stopped overnight after a machine reboot!

**Comment by pannon** [comment]
Please try enabling these sysctl's":

```           
net.inet.ip.forwarding=1
net.link.bridge.pfil_onlyip=0
net.link.bridge.pfil_bridge=0
net.link.bridge.pfil_member=0
```

**Comment by zenny** [comment]
Forgot to mention, they are already enabled. 

Without making any changes, the network inside the jail started working! So the jails are working in alternative days! 

However, I figured out the problem with this random behavior caused by the VNET bug. This seems to happen when the network stack is restarted '/etc/rc.d/netif restart' in the jail host with VNET enabled.

# uname -a
FreeBSD freebsd10-dev 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r280361: Mon Mar 23 10:58:32 CET 2015     root@freebsd10-dev:/usr/obj/usr/src/sys/IOCAGE  amd64

**Comment by pannon** [comment]
Closing this as this is not an issue in iocage.
