### ISSUE TITLE
iocage does not assign IPv6 addresses to interfaces (non-VNET jails)

### ISSUE THREAD

**Issue by grobe0ba** [pannon/iocage#62]
iocage 1.5.1 (2015/03/23)

As the subject says, when the jail starts, it does not assign an IPv6 address given in ip6_addr to the interface specified, e.g. ip6_addr="vlan1|2001:xxxx:xxxx::xxxx/xx".
This occurs regardless of whether or not an IPv4 address is also to be assigned.
The setting DOES appear in the jail configuration.

**Comment by skarekrow** [comment]
Hi can you reopen this in our new repo? github.com/iocage/iocage.

Thanks.
