### ISSUE TITLE
Can't start 9.3 jail with default options (host is 9.3 too)

### ISSUE THREAD

**Issue by mike-pt** [pannon/iocage#63]
jail: unknown parameter: allow.mount.tmpfs
jail: unknown parameter: mount.fdescfs
  ! Start                FAILED

How can I unset those? they are set to 0 but I would like to just not set them

**Comment by mike-pt** [comment]
actually "mount_fdescfs:1" but the question still applies.

tks

**Comment by skarekrow** [comment]
Hi can you reopen this in our new repo? https://www.github.com/iocage/iocage.

Thanks.
